apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bases

patchesJson6902:
- target:
    kind: custom-config
    name: security-config
  path: security_config.yml

validators:
- validator.yaml
